apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80        # Cluster 내부 포트
      targetPort: 3000  # Pod의 컨테이너 포트
      nodePort: 31000 # 외부에서 접근할 포트 (30000~32767 중 선택)