apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-app
  namespace: argocd  # Argo CD가 설치된 네임스페이스
spec:
  project: default
  source:
    repoURL: https://github.com/hyegyeong-kang/root_project.git
    targetRevision: main
    path: frontend/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend  # 백엔드 리소스를 배포할 네임스페이스
  syncPolicy:
    automated:       # 자동 동기화 옵션
      prune: true    # 리소스 삭제도 반영
      selfHeal: true # 드리프트 자동 복구
