# Prometheus가 어떤 메트릭을 어떻게 수집할지 설정하는 파일입니다.
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring    # Prometheus가 설치된 네임스페이스로 바꾸세요
data:
  prometheus.yaml: |-
    scrape_configs:
      - job_name: 'fastapi-backend'
        static_configs:
          - targets: ['192.168.56.201:30001']